name: Build and Release 2.7.*

on:
  push:
    branches: 
      - branch-2.7.*
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: RHEL
            package_extension: 'rpm'
          - platform: Ubuntu
            package_extension: 'jdeb'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set VERSION environment variable
        run: echo "VERSION=2.7.7.0.0" >> $GITHUB_ENV

      - name: Use VERSION environment variable
        run: echo "The version is $VERSION"

      - name: Build Package
        run: |
          mvn versions:set -DnewVersion=$VERSION
          pushd ambari-metrics
          mvn versions:set -DnewVersion=$VERSION
          popd
          mvn -B clean install ${{ matrix.package_extension }}:${{ matrix.package_extension }} -DnewVersion=$VERSION -DbuildNumber=${{ github.sha }} -DskipTests -Dpython.ver="python >= 2.6"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release $VERSION
          draft: false
          prerelease: false

      - name: Upload Package to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/*.${{ matrix.package_extension }}
          asset_name: $VERSION-${{ matrix.platform }}.${{ matrix.package_extension }}
          asset_content_type: application/octet-stream