name: Build and Release 2.7.*

on:
  push:
    branches: 
      - branch-2.7.*
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: RHEL
            package_extension: 'rpm'
          - platform: Ubuntu
            package_extension: 'deb'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Extract tag name
        id: get_version
        run: echo "VERSION=2.7.7" >> $GITHUB_ENV

      - name: Build Package
        run: |
          mvn versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}
          pushd ambari-metrics
          mvn versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}
          popd
          mvn -B clean install ${{ matrix.package_extension }}:${{ matrix.package_extension }} -DnewVersion=${{ steps.get_version.outputs.VERSION }} -DbuildNumber=${{ github.sha }} -DskipTests -Dpython.ver="python >= 2.6"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Package to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/*.${{ matrix.package_extension }}
          asset_name: ${{ steps.get_version.outputs.VERSION }}-${{ matrix.platform }}.${{ matrix.package_extension }}
          asset_content_type: application/octet-stream